--ROLE 사용
--15-14
--여러 권한을 한번 부여하려면 롤을 만들어야 한다.
CREATE ROLE ROLESTUDY;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;

--한번에 권한 부여
GRANT ROLESTUDY TO ORCLSTUDY;
--한번에 권한 제거
REVOKE ROLESTUDY FROM ORCLSTUDY;
--계정과 권한 함께 제거
DROP USER ORCLSTUDY CASCADE;
