--16-15 CASE문 (SWITCH CASE)

DECLARE
    V_SCORE NUMBER DEFAULT 87;
BEGIN
    CASE TRUNC(V_SCORE/10)
        WHEN 10 THEN DBMS_OUTPUT.PUT_LINE('A 학점');
        WHEN 8 THEN DBMS_OUTPUT.PUT_LINE('B 학점');
        ELSE DBMS_OUTPUT.PUT_LINE('F 학점');
     END CASE;
END;
/
