--TABLE 작성 방법

DROP TABLE TABLE_PK;

CREATE TABLE TABLE_PK(
LOGIN_ID VARCHAR2(20) PRIMARY KEY,
LOGIN_PWD VARCHAR2(20) NOT NULL,
TEL VARCHAR2(20)
);

CREATE TABLE TABLE_PK(
LOGIN_ID VARCHAR2(20),
LOGIN_PWD VARCHAR2(20),
TEL VARCHAR2(20),
PRIMARY KEY(LOGIN_ID)
);

SELECT * FROM TABLE_PK;
